export default {
    GET_GAMES_SUCCESS: 'GET_GAMES_SUCCESS',
    GET_GAMES_ERROR: 'GET_GAMES_ERROR',

    GET_STREAMS_SUCCESS: 'GET_STREAMS_SUCCESS',
    GET_STREAMS_ERROR: 'GET_STREAMS_ERROR',

    GET_STREAM_SUCCESS: 'GET_STREAM_SUCCESS',
    GET_STREAM_ERROR: 'GET_STREAM_ERROR',

    GET_MATCHES_SUCCESS: 'GET_MATCHES_SUCCESS',
    GET_MATCHES_ERROR: 'GET_MATCHES_ERROR',

    GET_LIVE_MATCHES_SUCCESS: 'GET_LIVE_MATCHES_SUCCESS',
    GET_LIVE_MATCHES_ERROR: 'GET_LIVE_MATCHES_ERROR',

    GET_MATCH_SUCCESS: 'GET_MATCH_SUCCESS',
    GET_MATCH_ERROR: 'GET_MATCH_ERROR',

    LOADER_START: 'LOADER_START',
    LOADER_FINISH: 'LOADER_FINISH',
}